## Copyright (c) 2021 KeaOS/3 developers and contributors

## This file includes, parses configuration and sets right compiler params.

ifeq ($(ARCH),)
$(error $$ARCH not specified)
endif

include scripts/Makefile.config.$(ARCH)
