## Copyright (c) 2021 KeaOS/3 developers and contributors
## SPDX-License-Identifier: GPL-3.0-or-later

build := -f $(srctree)/scripts/Makefile.build dir
real-prereqs = $(filter-out $(PHONY),$^)
newer-prereqs = $(filter-out $(PHONY),$?)
