## Copyright (c) 2021 KeaOS/3 developers and contributors
## SPDX-License-Identifier: GPL-3.0-or-later

## This file includes, parses configuration and sets right compiler params.

ifeq ($(ARCH),)
$(error $$ARCH not specified)
endif

include scripts/Makefile.config.$(ARCH)
